/**
 * Per-slug local images under `public/software-images/{slug}/`.
 * Generated by `scripts/download-software-images-unsplash.mjs`.
 */

import { linkForSoftwareRelated } from '../megaMenu'
import manifestJson from './softwareImageManifest.json'

export type PremiumPhotoPaths = {
  heroTeam: string
  financialReports: string
  dashboard: string
  teamMeeting: string
  ledgerOffice: string
}

export const PREMIUM_IMAGE_FALLBACK = '/accounts/hero-finance-team.jpg'

const MANIFEST = manifestJson as Record<string, PremiumPhotoPaths>

const SLUG_ALIASES: Record<string, string> = {
  'point-of-sale-software': 'point-of-sale-management-software',
  'sms-integration-system': 'integration-system',
  'oil-and-gas-business-management-software': 'fuel-tank-lorry-management-software',
  'petrol-gas-filling-station-software': 'petrol-gas-filling-station-software',
}

const LEGACY_PACK: PremiumPhotoPaths = {
  heroTeam: '/accounts/hero-finance-team.jpg',
  financialReports: '/accounts/financial-reports.jpg',
  dashboard: '/accounts/accounting-dashboard.jpg',
  teamMeeting: '/accounts/finance-team-meeting.jpg',
  ledgerOffice: '/accounts/ledger-documents.jpg',
}

export function getPremiumPhotoPaths(slug: string): PremiumPhotoPaths {
  const resolved = SLUG_ALIASES[slug] ?? slug
  return MANIFEST[resolved] ?? LEGACY_PACK
}

/** Source URLs on digitalmanager.ae — for maintainers / SEO traceability. */
export const PREMIUM_PAGE_SOURCE_MAP: Record<string, string> = {
  'accounts-management-software': 'https://www.digitalmanager.ae/accounts-management-software/',
  'inventory-management-software': 'https://www.digitalmanager.ae/',
  'production-management-software': 'https://www.digitalmanager.ae/',
  'point-of-sale-management-software': 'https://www.digitalmanager.ae/',
  'payroll-management-software': 'https://www.digitalmanager.ae/',
  'crm-software': 'https://www.digitalmanager.ae/',
  'integration-system': 'https://www.digitalmanager.ae/',
  'fbr-pos-integration-software': 'https://www.digitalmanager.ae/',
  'retail-management-software': 'https://www.digitalmanager.ae/',
  'petrol-pump-software': 'https://www.digitalmanager.ae/',
  'cloud-erp-software-for-textile-industries': 'https://www.digitalmanager.ae/',
  'knitting-dyeing-industry-software': 'https://www.digitalmanager.ae/',
  'logistics-transportation-software': 'https://www.digitalmanager.ae/',
  'cloud-erp-software-for-agriculture-business': 'https://www.digitalmanager.ae/',
  'poultry-control-shed-management-software': 'https://www.digitalmanager.ae/',
  'erp-software-for-real-estate-business': 'https://www.digitalmanager.ae/',
  'small-and-medium-business-erp-software': 'https://www.digitalmanager.ae/',
  'garments-manufacturing-software': 'https://www.digitalmanager.ae/',
  'lpg-business-software': 'https://www.digitalmanager.ae/',
  'software-for-visa-immigration-consultants': 'https://www.digitalmanager.ae/',
  'candy-and-confectionery-manufacturing-software': 'https://www.digitalmanager.ae/',
  'oil-and-gas-business-management-software': 'https://www.digitalmanager.ae/',
}

export function getSourceMapUrl(slug: string): string {
  return PREMIUM_PAGE_SOURCE_MAP[slug] ?? 'https://www.digitalmanager.ae/'
}

export function relatedToIndustryLinks(
  related: { kind: 'module' | 'industry'; slug: string; label: string }[],
): { label: string; to: string }[] {
  return related.slice(0, 10).map((r) => ({
    label: r.label,
    to: linkForSoftwareRelated(r),
  }))
}
